owner: iqbalbinsb
repo: monitor

sites:
  - name: WWWMK
    url: $WWWMK
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 3000
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

  - name: MAINK
    url: $MAINK
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 3000
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

  - name: STATK
    url: $STATK
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 3000
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

  - name: CTTNK
    url: $CTTNK
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 3000
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

  - name: CONSOLE-IDCH
    check: "tcp-ping"
    url: $CONSOLE_IDCH
    port: 443
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 3000

status-website:
  cname: monitor.aliqbal.net
  favicon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/uptime.png
  logoUrl: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/uptime.png
  name: Uptime Monitor
  theme: night
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "botsb"
  commitAuthorEmail: "$BOTSB"

i18n:
  footer: Halaman ini menampilkan status layanan dan proyek yang saya pantau
  
robotsText: "User-agent: * \n Disallow: /"
