owner: iqbalbinsb
repo: monitor

sites:    
  - name: Console IDCH
    check: "tcp-ping"
    url: $CONSOLE_IDCH
    port: 443
    icon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/web.png
    maxResponseTime : 5000
    __dangerous__body_down_if_text_missing: '"status":"UP"'

status-website:
  cname: monitor.aliqbal.net
  favicon: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/uptime.png
  logoUrl: https://raw.githubusercontent.com/iqbalbinsb/monitor/master/assets/uptime.png
  name: Uptime Monitor
  theme: night
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: Halaman ini menampilkan status layanan dan proyek yang saya pantau
