owner: iqbalbinsb
repo: monitor

sites:
  - name: WWWMK
    url: $WWWMK

status-website:
  cname: monitor.aliqbal.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor
  navbar:
    - title: Monitor
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
